update files pulled via gget

diff --git a/.github/workflows/gget-update.yml b/.github/workflows/gget-update.yml
--- a/.github/workflows/gget-update.yml
+++ b/.github/workflows/gget-update.yml
@@ -1,10 +1,10 @@
 #
 #    __                          __
-#   / /____ ___ ____  ___  ___ _/ /       This script is provided to you by https://github.com/tegonal/github-commons
-#  / __/ -_) _ `/ _ \/ _ \/ _ `/ /        It is licensed under Creative Commons Zero v1.0 Universal
+#   / /____ ___ ____  ___  ___ _/ /       This script is provided to you by https://github.com/tegonal/gget
+#  / __/ -_) _ `/ _ \/ _ \/ _ `/ /        It is licensed under Apache 2.0
 #  \__/\__/\_, /\___/_//_/\_,_/_/         Please report bugs and contribute back your improvements
 #         /___/
-#                                         Version: v0.5.0-SNAPSHOT
+#                                         Version: v0.7.4
 #
 ###################################
 name: "gget update"
@@ -39,9 +39,9 @@ jobs:
           wget "https://raw.githubusercontent.com/tegonal/gget/main/install.sh.sig" && \
           gpg --homedir ./gpg --verify ./install.sh.sig ./install.sh && \
           chmod +x ./install.sh && \
-          echo "verification successful" && verificationResult=true || (echo "verification failed, don't continue"; exit 1) && \
-          ./install.sh && \
-          false || cd "$currentDir" && rm -r "$tmpDir" && "${verificationResult:-false}"
+          echo "verification successful" || (echo "verification failed, don't continue"; exit 1) && \
+          ./install.sh && result=true || (echo "installation failed"; exit 1) && \
+          false || cd "$currentDir" && rm -r "$tmpDir" && "${result:-false}"
           # end install.doc.sh
       - name: reset gpg keys
         run: gget reset --gpg-only true
