update gt to v0.12.0

diff --git a/.github/workflows/gt-update.yml b/.github/workflows/gt-update.yml
--- a/.github/workflows/gt-update.yml
+++ b/.github/workflows/gt-update.yml
@@ -4,16 +4,13 @@
 #  / __/ -_) _ `/ _ \/ _ \/ _ `/ /        It is licensed under Apache License 2.0
 #  \__/\__/\_, /\___/_//_/\_,_/_/         Please report bugs and contribute back your improvements
 #         /___/
-#                                         Version: v0.10.2
+#                                         Version: v0.12.0
 #
 ###################################
 name: "gt update"
 on:
   schedule:
     - cron: '0 4 * * MON'
-  push:
-    branches:
-      - do-gt-update
   workflow_dispatch:
 
 jobs:
@@ -21,8 +18,13 @@ jobs:
     runs-on: ubuntu-latest
     if: github.repository_owner == 'tegonal'
     steps:
-      - name: Import gpg key(s) defined in secrets.PUBLIC_GPG_KEYS_WE_TRUST
-        run: gpg --import - <<< "${{ secrets.PUBLIC_GPG_KEYS_WE_TRUST }}"
+      - name: Import gpg key(s) defined in vars.PUBLIC_GPG_KEYS_WE_TRUST and secrets.PUBLIC_GPG_KEYS_WE_TRUST
+        run: |
+          gpg --import - <<< "${{ vars.PUBLIC_GPG_KEYS_WE_TRUST }}" && success=true \
+            || (echo "could not import GPG keys via vars.PUBLIC_GPG_KEYS_WE_TRUST -- maybe it's not defined"; exit 1) && \
+          false || gpg --import - <<< "${{ secrets.PUBLIC_GPG_KEYS_WE_TRUST }}" && success=true \
+            || (echo "could not import GPG keys via secrets.PUBLIC_GPG_KEYS_WE_TRUST -- maybe it's not defined"; exit 1) && \
+          false || "${success:-false}" && echo "was able to import GPGs either via vars or secrets (or via both -- see above)"
       - uses: actions/checkout@v3
       - name: Install gt
         run: |
@@ -51,7 +53,7 @@ jobs:
       - name: git status
         run: git status
       - name: Create pull request if necessary
-        uses: peter-evans/create-pull-request@v5
+        uses: peter-evans/create-pull-request@v4
         with:
           branch: gt/update
           base: main
